### ISSUE TITLE
关于反代

### ISSUE THREAD

**Issue by kylinpoet** [lyy0709/cockroachai-oauth#1]
你好，请问下，如果不添加反代，直接ip:port 可以吗？
cockroachai已经添加oauth地址了，但输入任意6位不能登录，只能输入原token登录

**Comment by lyy0709** [comment]
理论上可以但不建议，如果公益模式请输入cockroachai上写的OAUTH_URL: http://127.0.0.1:9000/oauth,则随便输入六位token可登录
